In [1]:
% matplotlib inline

In [6]:
import mykf
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
reload(mykf)

<module 'mykf' from 'mykf.pyc'>

In [7]:
cross, clf, df = mykf.crosstab()

In [8]:
print(cross)

predicted    1    2    3    4    5    6
actual                                 
1          447    5    4    0    1    0
2            6  351    7    0    0    0
3            8   12  318    0    0    0
4            0    0    0  435   36    0
5            0    0    0   35  401    0
6            0    0    0    1    0  453


In [9]:
tot = 0
tot_correct = 0

for ind, val in enumerate(cross.columns.values):
    for amt in cross.iloc[ind]:
#         print(amt)
        tot += amt
#    print(cross.iloc[ind])
# print(tot)

for col in cross.columns.values:
    correct_pred = cross.loc[col][col] # gives diagonal
#     print(correct_pred)
    tot_correct += correct_pred
    
print('total correct: {}'.format(tot_correct))
print('total items: {}'.format(tot))
print('Model accuracy: {}'.format(100.000 * tot_correct / tot))

# print('Accuracy of model = {:f}'.format(float(tot_correct)) / float(tot))

total correct: 2405
total items: 2520
Model accuracy: 95.4365079365


In [10]:
from sklearn.model_selection import KFold
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([1, 2, 3, 4])
kf = KFold(n_splits=2)
kf.get_n_splits(X)


2

In [11]:
kf

KFold(n_splits=2, random_state=None, shuffle=False)

In [12]:
X


array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [13]:
for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)

('TRAIN:', array([2, 3], dtype=int64), 'TEST:', array([0, 1], dtype=int64))
('TRAIN:', array([0, 1], dtype=int64), 'TEST:', array([2, 3], dtype=int64))


In [15]:
mysplit = kf.split(X)

In [18]:
for item in mysplit:
    print(item)

(array([2, 3], dtype=int64), array([0, 1], dtype=int64))
(array([0, 1], dtype=int64), array([2, 3], dtype=int64))


In [23]:

# df['is_train'] = np.random.uniform(0, 1, len(df)) <= .75
df['is_train'] = np.random.uniform(0, 1, len(df)) <= .75
# df['species'] = pd.Factor(iris.target, iris.target_names)
# df['act2'] = pd.Categorical.from_codes(df.act_num, labels)

train, test = df[df['is_train']==True], df[df['is_train']==False]

features = df.columns[:4]
clf = RandomForestClassifier(n_jobs=2)
y, _ = pd.factorize(train['activity'])
clf.fit(train[features], y)

# Kyle's code starts here
preds = labels[clf.predict(test[features])] #ask kyle about features

s1 = pd.Series(test['activity'])
s2 = pd.Series(preds)
s2.index = np.arange(len(s2)) # This index needs to be reset
s1.index = np.arange(len(s1)) # This one doesn't have to be
result_df = pd.concat([s1, s2], axis=1)
result_df.columns = ['actual', 'predicted']

cross = pd.crosstab(result_df.actual, result_df.predicted)


NameError: name 'RandomForestClassifier' is not defined